# Generated by Django 3.1.3 on 2020-11-26 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import plots.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('info', plots.utils.JSONField()),
                ('size', models.FloatField()),
                ('region', models.CharField(max_length=20)),
                ('habitat_type', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('imageURL', models.URLField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
