# Generated by Django 3.1.3 on 2020-11-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=45, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plot',
            name='lng',
            field=models.DecimalField(decimal_places=6, default=14, max_digits=9),
            preserve_default=False,
        ),
    ]
