# Generated by Django 3.1.3 on 2020-12-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0003_auto_20201126_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='imageURL',
            field=models.URLField(blank=True),
        ),
    ]
