# Generated by Django 3.1.3 on 2020-12-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0004_auto_20201207_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='imageURL',
            field=models.URLField(blank=True, null=True),
        ),
    ]
